### PR TITLE
Fix: ProfileSummary vertical alignment

### LINKED ISSUE #202: Fix: ProfileSummary card has wrong vertical alignment
Based on the design this is how it should look vs how it looks:

| Expected | Actual | 
|---|---|
| Screenshot 2024-07-02 at 10 51 25 | Screenshot 2024-07-02 at 10 51 54 |

The text composables should be centered, not top aligned.

### PR DESCRIPTION
**Pull request by AdamGrzybkowski**
Closes #202

### Description

The `ProfileSummary` component has a wrong alignment of the name/location/button combo. Here's the visual comparison:
| Expected | Actual | 
|---|---|
| Screenshot 2024-07-02 at 10 51 25 | Screenshot 2024-07-02 at 10 51 54 |

This PR updates it to follow the design:

| Location | Without location |
|---|---|
| Screenshot 2024-07-02 at 12 12 10 | Screenshot 2024-07-02 at 12 12 21 |

### Testing Steps

There's a new test screenshot to cover that scenario but if you want to test it yourself here are the steps:
1. Go to gravatar.com and remove the location from your profile
2. Open the demo app
3. Go to the profile tab and fetch your profile
4. Confirm the UI looks as it should - text composables are center aligned
5. Go to gravatar.com and add the location to your profile 
6. Back to the demo app
7. Go to the profile tab and fetch your profile
8. Confirm the UI looks as it should

### CODE REVIEW

File: gravatar-ui/src/main/java/com/gravatar/ui/components/ProfileSummary.kt [hunk 1]
```diff
@@ -68,27 +70,18 @@ public fun ProfileSummary(
...
-                            }
-
-                            ComponentState.Loading -> {
-                                Location(state = state, skeletonModifier = Modifier.fillMaxWidth(0.9f))
-                            }
-
-                            ComponentState.Empty -> {
-                                Location(state)
-                            }
-                        }
```
Comment (AdamGrzybkowski) [inline gravatar-ui/src/main/java/com/gravatar/ui/components/ProfileSummary.kt:91]: This was pretty much a copy-paste of the `Location` component so I removed it from here. I guess this is a leftover.

**Review by hamorillo — APPROVED** [review]
Looks nice! :shipit:
