### PR TITLE
QuickEditor: Fix `AvatarStorage.updateAvatar` to not override the `selected` value 

### LINKED ISSUE #526: QuickEditor: AvatarStore.updateAvatar should omit selected value
When updating an avatar, the `selected` information is not returned. Therefore, the `AvatarStorage` can't just use the returned object; we need to use the `selected` value from the previously stored object.

### PR DESCRIPTION
**Pull request by hamorillo**
Closes #526 

### Description

The `PATCH` to update avatars doesn't receive the email, so, in the backend, we can't decide if that's the avatar selected for the email we are working with.

In the `AvatarStorage.updateAvatar` method, we should only use the value from the `updatedAvatar` if it's not `null`. Otherwise, we should keep the stored avatar's selected value.

<details>
<summary> Before </summary>

https://github.com/user-attachments/assets/3b2fe41b-13a7-41c8-b585-4d33588540f8
</details>

<details>
<summary> After </summary>

https://github.com/user-attachments/assets/f30f84e1-ff05-4b5c-853d-1fb5803c0a7e
</details>

### Testing Steps

1. Open the QE
2. Select an avatar (if you don't have one selected already)
3. Modify the rating of the selected avatar
4. Verify that you still see the avatar as selected when the rating is modified
5. Open the AltTextPage and modify the AltText for the selected avatar
6. Verify that you still see the avatar as selected when the AltText is modified

### CODE REVIEW

File: gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/data/storage/AvatarStorage.kt [hunk 1]
```diff
@@ -73,7 +73,9 @@ internal class AvatarStorage {
             val avatars = avatarsFlow.replayCache.lastOrNull()?.let {
                 it.map { avatar ->
                     if (avatar.imageId == avatarToUpdate.imageId) {
-                        avatarToUpdate
+                        // If the avatarToUpdate has a selected value, use it.
+                        // Otherwise, use the stored avatar selected value.
+                        avatarToUpdate.copy(selected = avatarToUpdate.selected ?: avatar.selected)
```
Comment (AdamGrzybkowski) [inline gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/data/storage/AvatarStorage.kt:78]: 💡 This solution works but I see a potential issue. This would stop working if backend started sending back the `selcted` value as false instead of null. If we only copied here the values that can actually change (rating and the alt_text) we would be much safer.

This might be unlikely scenario, but technically could happen. 

WDYT?

**Review by AdamGrzybkowski — COMMENTED** [review]
Great this requires modification only at the storage level!

File: gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/data/storage/AvatarStorage.kt (hunk 1 above)
Comment (hamorillo) [reply gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/data/storage/AvatarStorage.kt:78]: > This would stop working if backend started sending back the selcted value as false instead of null.

In my opinion, that would be a bug on the backend because, as we've seen, we don't know if it is selected or not. If the backend sends that value as `false/true,` it is because that's the correct value, and we should update it.

Anyway, I'm not entirely against only updating rating and alt_text, but I was looking at the `updateAvatar` method as a more abstract one that, if, for example, the URL changes, can update the URL too. (Just as an example). 

I can refactor this if you still feel that approach is much safer. 🙂

Comment (AdamGrzybkowski) [reply gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/data/storage/AvatarStorage.kt:78]: >In my opinion, that would be a bug on the backend because, as we've seen, we don't know if it is selected or not. If the backend sends that value as false/true, it is because that's the correct value, and we should update it.

I agree. 

>I can refactor this if you still feel that approach is much safer.

No need to, let's stick with this one.

**Review by AdamGrzybkowski — APPROVED** [review]
